### ISSUE TITLE
The dataset and code

### ISSUE THREAD

**Issue by sinemaslanx** [joannahong/text-based-dataset-with-comprehensive-facial-expression-sentence#2]
Hello Joanna,
I couldn't find the code and dataset on this GitHub page. Will you publish them? I would greatly appreciate it if you could share, so we can try your method on our data, of course citing your work. If you prefer, my e-mail address is siinem@gmail.com 

Best
Sinem

**Comment by joannahong** [comment]
Hello,
Regarding datasets, they are public datasets so I have no permission to directly provide the datasets. You need to download through each provided dataset hompage.
I am working on providing codes, so I would like to ask you to wait for them.
