### ISSUE TITLE
How do u generate the text?

### ISSUE THREAD

**Issue by TiankaiHang** [joannahong/text-based-dataset-with-comprehensive-facial-expression-sentence#3]
Hi,

Thanks for your nice work!! I have one question. How do u get the text? Do u generate them by some rules or do u just ask people to do manual annotation?

Best,
Tiankai

**Comment by joannahong** [comment]
Hello,

I generated them by rules through python code, by randomly selecting descriptions that correspond to the given facial image.

Thank you!
